// Generated by strapi-frontend. Re-run `npx strapi-frontend` to update.
import type { Schema } from '@strapi/strapi'
type Schemas = Schema.Schemas
import type {
  InferComponent,
  InferDoc,
  Payload,
  StrapiBase,
  StrapiListResponse,
  StrapiMedia,
  StrapiSingleResponse,
} from 'strapi-frontend'

// ─── Components ──────────────────────────────────────────────────────────────

export type OrderDeliveryAddress = InferComponent<Schemas['order.delivery-address']>
export type ProductSpecification = InferComponent<Schemas['product.specification']>
export type ProductVariant = InferComponent<Schemas['product.variant']>

// ─── Content Types ───────────────────────────────────────────────────────────

export type Category = InferDoc<Schemas['api::category.category']>

export type Order = InferDoc<Schemas['api::order.order'], {
  items: OrderItem[]
  deliveryAddress: OrderDeliveryAddress
}>

export type OrderItem = InferDoc<Schemas['api::order-item.order-item'], {
  product: Product | null
  order: Order | null
}>

export type Product = InferDoc<Schemas['api::product.product'], {
  category: Category | null
  specifications: ProductSpecification[]
  variants: ProductVariant[]
}>

export type { Payload, StrapiBase, StrapiMedia, StrapiListResponse, StrapiSingleResponse }